### ISSUE TITLE
enhancement - build project by Dockerfile 

### ISSUE THREAD

**Issue by johndpope** [dan-nadler/ParseyAPI#1]
I drafted this Dockerfile for another project 
https://github.com/dmansfield/parsey-mcparseface-api/issues/1
It does build as long as you throw enough RAM at it.
https://gist.github.com/johndpope/d41a7d6daf8652cbdaff41a2b063c801

**Comment by dan-nadler** [comment]
Oh great, I'll take a look. 

I was able to get Parsey to build on an EC2 instance (I think I needed one with 12 GB of RAM). Then, made an image of that instance and used it to boot up a t2.nano (IIRC) with Parsey already built. That worked fine for my purposes, and was why I ended up building this little (and completely undocumented) API.

**Comment by johndpope** [comment]
slightly exasperating. 
https://gist.github.com/johndpope/5772af264aa1495ed2a5a192019513e1
